### PR TITLE
Existance checks for create and drop enums and cascade: true for drop_enum

### PR DESCRIPTION
**Pull request by hosembafer**
#24 

# What's inside
- [x] add `if_not_exists: true` option to create_enum
- [x] add `if_exists: true` option to drop_enum
- [x] add `cascade: true` to drop_enum

# Checklist:
- [x] I have added tests

### CODE REVIEW

**Comment by hosembafer** [comment]
Also, would be nice to document if_not_exists, if_exists, cascade or it's enough to rely on Github's hover tooltip annotation?

**Comment by bibendi** [comment]
Wow! Brilliant!
I don't know what Github's hover tooltip annotation is, but any documentation is always desirable. So, as you wish :)

**Comment by hosembafer** [comment]
When hovering on code snippet more than 1-2 sec, tooltip appearing.
I think would be better to issue a new ticket and improve API documentation overall if you think so.

github-tooltip-annotation

**Comment by bibendi** [comment]
Got it!

**Pull request merged**
