### PR TITLE
Update README with instructions for adding an enum column to an existing table

### PR DESCRIPTION
**Pull request by kaka-ruto**
## Context

Updates the README to show how to add an enum column to an existing table

## Related tickets

#8 

## What's inside

- [x] Added documentation to show the same
- [x] Moved the `rename_enum_value` example docs to a paragraph before the Postgres NB note, for a good flow
- ...

## Checklist:

- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by bibendi** [comment]
Interesting! Could you add a test?
https://github.com/bibendi/activerecord-postgres_enum/blob/master/spec/active_record/migrations_spec.rb

**Comment by kaka-ruto** [comment]
Hi @bibendi , I am getting a little trouble setting up. Could you please indicate how to setup the database, including management of env variables like DATABASE_URL? That will be really helpful. Also seeing some docker files, should we run it using docker? That info will help a lot.

I appreciate your help

**Comment by bibendi** [comment]
I'm using Docker for all projects which I'm working with.

> should we run it using docker?

You can, but this is not an obligation. You can run tests without using Docker as well.

So, to run tests in Docker you need:
- Install Docker
- Install Docker Compose
- Install DIP https://github.com/bibendi/dip
- Run `dip provision`
- Run `dip rspec` to check on the latest Rails
- Run `dip appraisal rspec` to check on all supported Rails

**Comment by kaka-ruto** [comment]
I managed to set up and add a few tests.

The tests that check an enum is created and added to an existing table pass, but the one that tests for absence of enums after a down migration fail.

I tried adding an implementation to remove the enum on a down migration but I quite didn't get it.

Your advise is awaited :)

**Comment by bibendi** [comment]
Looks good so far! I'll go on vacation tomorrow. I hope I'll have a time next week to investigate the problem.

**Comment by kaka-ruto** [comment]
Thanks. Let me know how I can help once you're back. Enjoy your vacation :)

**Comment by kaka-ruto** [comment]
Hey, looks like this no longer works. Just created an enum in a similar manner and the enum is not created, with no errors reported.

**Comment by kaka-ruto** [comment]
Never mind, that was an issue with my own migrations that was making the file not be reached.

**Comment by bibendi** [comment]
@kaka-ruto Thank you!

**Pull request merged**
